### ISSUE TITLE
Make SHA compliant variants

### ISSUE THREAD

**Issue by fionafibration** [ctz/keccak#3]
Hello, 
I'm writing an educational, hybrid cryptosystem in pure python and was wondering what, if any, changes i'd need to make to make this Keccak implementation SHA-3 compliant. 
I think having a simple, working SHA-3 implementation would be great. 
Your project is the only one I could find which implemented Keccak in Python 3+ under around 600 lines. My project is designed to showcase the principles of a modern, hybrid cryptosystem while keeping cryptographic operations easily readable in source files. 
Thanks, 
Fin

**Comment by ctz** [comment]
Thanks -- merged in #6.
